# Generated by Django 4.2.5 on 2023-09-26 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributor',
            new_name='Author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='contributors',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reviews.author'),
        ),
        migrations.DeleteModel(
            name='BookContributor',
        ),
    ]
