# Generated by Django 4.2.5 on 2023-10-31 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_tagcolor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TagColor",
        ),
    ]
