# Generated by Django 4.2.5 on 2023-09-30 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_author_email_remove_publisher_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='book',
            name='summary',
        ),
        migrations.AddField(
            model_name='author',
            name='name',
            field=models.CharField(default=None, help_text='The name of the author', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0, help_text='The rating of the book'),
        ),
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default=None, help_text='Link to the book page on Goodreads'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.author'),
        ),
    ]
