# Generated by Django 4.2.5 on 2023-09-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_remove_author_first_name_remove_author_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(default=None, help_text='Link to the book page on Goodreads', null=True),
        ),
    ]
