# Generated by Django 4.2.5 on 2023-11-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_remove_booklist_book_titles_booklist_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='list_cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
