# Generated by Django 4.2.5 on 2023-10-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
