# Generated by Django 4.2.5 on 2023-11-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_rename_booklist_bookslist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooksList',
            new_name='BookCollection',
        ),
    ]
