# Generated by Django 4.2.5 on 2023-10-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_book_cover_book_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rating',
            new_name='rating_small',
        ),
    ]
