# Generated by Django 4.2.5 on 2023-10-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_rename_rating_book_rating_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.CharField(blank=True, help_text='Genres of the book', max_length=1000, null=True),
        ),
    ]
