# Generated by Django 4.2.5 on 2023-11-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0013_book_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="likes",
        ),
    ]
