# Generated by Django 4.2.5 on 2023-10-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_alter_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.CharField(default=None, help_text='The rating of the book', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating_small',
            field=models.CharField(default=None, help_text='The smaller rating of the book', max_length=50),
        ),
    ]
