# Generated by Django 4.2.5 on 2023-11-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_snippet_user'),
        ('reviews', '0015_book_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='book_likes', to='members.profile'),
        ),
    ]
