# Generated by Django 4.2.5 on 2023-12-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_alter_book_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='likes',
        ),
    ]
