# Generated by Django 4.2.5 on 2023-10-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_alter_book_rating_alter_book_rating_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.CharField(blank=True, help_text='The rating of the book', max_length=50, null=True),
        ),
    ]
