# Generated by Django 4.2.5 on 2023-10-11 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_alter_book_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
    ]
