# Generated by Django 4.2.5 on 2024-06-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0019_book_part_of_series"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthorImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(upload_to="uploads/")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="best_books_of_2023",
        ),
    ]
