# Generated by Django 4.2.5 on 2023-10-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_remove_book_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='cover_url',
        ),
    ]
