# Generated by Django 4.2.5 on 2023-10-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_review_written_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(help_text='The rating the reviewer has given.', max_length=10),
        ),
    ]
