# Generated by Django 4.2.5 on 2023-10-15 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='book',
            field=models.ForeignKey(help_text='The Book that this review is for.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.book'),
        ),
    ]
