# Generated by Django 4.2.5 on 2023-10-18 06:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0026_review_likes_reviewcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='review_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
