# Generated by Django 4.2.5 on 2023-10-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_sharedreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rating_small',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.AddField(
            model_name='book',
            name='amazon_link',
            field=models.URLField(blank=True, help_text='Buy on Amazon.', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='audible_link',
            field=models.URLField(blank=True, help_text='Buy on Amazon.', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(blank=True, help_text='Number of pages in the book.', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.CharField(blank=True, help_text='Genres of the book (tags)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='time',
            field=models.CharField(blank=True, help_text='Time to finish the book.', max_length=30, null=True),
        ),
    ]
