# Generated by Django 4.2.5 on 2024-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_profile_books_liked"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
