# Generated by Django 4.2.5 on 2023-10-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_rename_cover_book_cover_url'),
        ('members', '0007_profile_facebook_link_profile_homepage_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='books_bookmarked',
            field=models.ManyToManyField(blank=True, related_name='bookmarks', to='reviews.book'),
        ),
        migrations.AddField(
            model_name='profile',
            name='books_read',
            field=models.ManyToManyField(blank=True, related_name='read_books', to='reviews.book'),
        ),
    ]
